---
- name: debug module demo
  hosts: all
  vars:
          fruit: "apple"
  tasks:
          - name: debug messgage
            debug:
                    msg: "our fruit is {{ fruit }}"
                    verbosity: 2
