---
- name: demo to reboot 
  hosts: all
  tasks:
          - name: reboot hosts
            reboot:
                    msg: "rebbot by ansible"
                    pre_reboot_delay: 5
                    post_reboot_delay: 10
                    test_command: "whoami"
